
#Autogenerated github autocomplete function
_git_autocomplete()
{   
    cur=${COMP_WORDS[COMP_CWORD]};
    COMPREPLY=( $(compgen -W "$(github-autocomplete ${COMP_WORDS[COMP_CWORD]})" -- $cur) )
}
complete -o filenames -F _git_autocomplete git clone