
#Autogenerated github autocomplete function
_git_autocomplete()
{   
    COMPREPLY=( $(compgen -W "$(github-autocomplete search ${COMP_WORDS[COMP_CWORD]})" -- ${COMP_WORDS[COMP_CWORD]}) )
}
complete -o filenames -F _git_autocomplete git clone